### ISSUE TITLE
When test dataset no label, how refine will predict?

### ISSUE THREAD

**Issue by Aksox** [Wuyxin/ReFine#18]
I read refine model codes, that's an excellent project. And, I want to know when test dataset no label, how refine will predict? (In station of mutag) I see codes in https://github.com/Wuyxin/ReFine/blob/main/explainers/refine.py#L118 in get_mask() method when gets mask using labels.

**Comment by Wuyxin** [comment]
Hi, 

Thanks!

As we are explaining the deep models, the label of interest will be the model prediction hat_Y. 

Besides, here we only consider the explainer's performance in explaining instances with the right predictions, where hat_Y=Y. Thus we simply use Y (graph.y) in the code.

But I realize it may confuse, and could be problematic if the test dataset has no label (especially in practice). 

I will update the code soon and replace it with model prediction instead of the label.

**Comment by Wuyxin** [comment]
Code updated. Now `hat_y` will be the label to explain (cf. [refine.py#L63](https://github.com/Wuyxin/ReFine/blob/e1fb85a9d71cd0654159e4bfeb65b32530422286/explainers/refine.py#L63))
